name: BucketMCVoteListener
version: ${project.version}
main: me.votelistener.bmc.bucketmcvotelistener.BucketMCVoteListener
api-version: 1.13
authors: [VinnieMaen]
description: VoteLIstener
depends: [Votifier]
commands:
  vote:
    description: Vote for the server!
